static const char *RcsId = "$Id:  $";
//+=============================================================================
//
// file :         BeamPositionTracking.cpp
//
// description :  C++ source for the BeamPositionTracking and its commands. 
//                The class is derived from Device. It represents the
//                CORBA servant object which will be accessed from the
//                network. All commands which can be executed on the
//                BeamPositionTracking are implemented in this file.
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :    Synchrotron SOLEIL 
//               L'Orme des merisiers - Saint Aubin
//               BP48 - 91192 Gif sur Yvette
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================



//===================================================================
//
//	The following table gives the correspondence
//	between commands and method name.
//
//  Command name               |  Method name
//	----------------------------------------
//  State                      |  dev_state()
//  Status                     |  dev_status()
//  ActuatorSystemCalibration  |  actuator_system_calibration()
//  StartBeamTracking          |  start_beam_tracking()
//  StopBeamTracking           |  stop_beam_tracking()
//  AcknowlegeStep             |  acknowlege_step()
//
//===================================================================


#include <tango.h>
#include <BeamPositionTracking.h>
#include <BeamPositionTrackingClass.h>
#include <yat/utils/StringTokenizer.h>

// Token separator for PS property.
#define kTOKEN_SEPARATOR std::string("::")
//Simulated mode strings
#define SIMULATED_MODE std::string("SIMULATED")
#define NORMAL_MODE std::string("NORMAL")
namespace BeamPositionTracking_ns
{

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::BeamPositionTracking(string &s)
// 
// description : 	constructor for simulated BeamPositionTracking
//
// in : - cl : Pointer to the DeviceClass object
//      - s : Device name 
//
//-----------------------------------------------------------------------------
BeamPositionTracking::BeamPositionTracking(Tango::DeviceClass *cl,string &s)
:Tango::Device_4Impl(cl,s.c_str())
{
	init_device();
}

BeamPositionTracking::BeamPositionTracking(Tango::DeviceClass *cl,const char *s)
:Tango::Device_4Impl(cl,s)
{
	init_device();
}

BeamPositionTracking::BeamPositionTracking(Tango::DeviceClass *cl,const char *s,const char *d)
:Tango::Device_4Impl(cl,s,d)
{
	init_device();
}
//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::delete_device()
// 
// description : 	will be called at device destruction or at init command.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::delete_device()
{
	//	Delete device allocated objects
	if (m_taskManager)
		delete m_taskManager;
	if (m_dynAttrManager)
		delete m_dynAttrManager;

	//- remove the DeviceInfo
    yat4tango::DeviceInfo::release(this);
    //- remove the InnerAppender
    yat4tango::InnerAppender::release(this);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::init_device()
// 
// description : 	will be called at device initialization.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::init_device()
{
	INFO_STREAM << "BeamPositionTracking::BeamPositionTracking() create device " << device_name << endl;

	// Initialise variables to default values
	//--------------------------------------------
	get_device_property();

	// Initialize Members
	m_initDone = false;
	m_computedTime = 0;
	m_taskManager = 0;
	m_dynAttrManager = 0;
	m_target.xTargetPoint = 0;
	m_target.yTargetPoint = 0;
	m_warningZone.xCenter = 0;
	m_warningZone.yCenter = 0;
	m_warningZone.radius = 0;
	m_xBeamPositionInPixels = 0;
	m_yBeamPositionInPixels = 0;
	
	BPTTaskManager::PIDCoefficient xAxisPID;
	BPTTaskManager::PIDCoefficient yAxisPID;

	INFO_STREAM << "Create the InnerAppender in order to manage logs." << endl;
    yat4tango::InnerAppender::initialize(this, 512);

	INFO_STREAM << "Create the DeviceInfo in order to manage info on versions." << endl;
    yat4tango::DeviceInfo::initialize( this, YAT_XSTR(PROJECT_NAME), YAT_XSTR(PROJECT_VERSION));
    yat4tango::DeviceInfo::add_dependency(this, "BeamPositionTracking ", YAT_XSTR(beamPositionPointing_PROJECT_VERSION));


	bool simulated_mode = false;
	//Simulated mode 
	if (deviceMode == NORMAL_MODE)
		simulated_mode = false;
	else
		simulated_mode = true;

	//Extract PIDs informations
	try{
		xAxisPID = extractPIDCoeffients(xPIDDefinition);
		yAxisPID = extractPIDCoeffients(yPIDDefinition);
	}catch(std::invalid_argument &iaE){
        set_status ("Initialization error [PID definition not correct, has to be written this way : 'true::1::2::3']");
        set_state (Tango::FAULT);
        return;
	}

	// Creation of dynAttrManager
	try{
		if (!m_dynAttrManager)
			m_dynAttrManager = new yat4tango::DynamicAttributeManager(this);

	}catch( Tango::DevFailed& df ){
        ERROR_STREAM << df << std::endl;
        set_status ("Initialization error [Tango Exception caught while instantiating DynamicAttributeManager]");
        set_state (Tango::FAULT);
        return;
    }
    catch(...){
        std::string err_msg = "Initialization error [unknown exception caught while instantiating DynamicAttributeManager]";
        ERROR_STREAM << err_msg << std::endl;
        set_status (err_msg);
        set_state (Tango::FAULT);
        return;
    }

	// Creation of BPTTaskManager
	try{
		if (!m_taskManager)
			m_taskManager = new BPTTaskManager::BPTTaskManager(this, m_dynAttrManager, sensorPluginType, pluginPath, 
																	actuatorSystemDeviceAdress,
																	xAxisPID, yAxisPID,
																	calibrationStepNbXAxis, calibrationStepNbYAxis,
																	nbImgToAlign, deviceTaskPeriod, simulated_mode);

	}catch( Tango::DevFailed &df ){
        ERROR_STREAM << df << std::endl;
        set_status ("Initialization error [Tango Exception caught while instantiating BPTTaskManager]");
        set_state (Tango::FAULT);
        return;
    }
    catch(...){
        std::string err_msg = "Initialization error [unknown exception caught while instantiating BPTTaskManager]";
        ERROR_STREAM << err_msg << std::endl;
        set_status (err_msg);
        set_state (Tango::FAULT);
        return;
    }

    // Start BPTTaskManager
    try
    {
        if (m_taskManager)
			m_taskManager->go(3000);
		
        set_state(Tango::INIT);
        set_status("Device initialisation started...");
    }
    catch( Tango::DevFailed &df )
    {
        ERROR_STREAM << df << std::endl;
        set_status ("Initialization error [Tango Error: " +  std::string(df.errors[0].desc) + ", while starting BPTTaskManager]");
        set_state (Tango::FAULT);
        m_taskManager = NULL;
        return;
    }
    catch(...)
    {
        std::string err_msg = "Initialization error [Unknown Error while starting BPTTaskManager]";  
        ERROR_STREAM << err_msg << std::endl;
        set_status (err_msg);
        set_state (Tango::FAULT);
        m_taskManager = NULL;
        return;
    }

    m_initDone = true;
    
}


//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::get_device_property()
// 
// description : 	Read the device properties from database.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::get_device_property()
{
	//	Initialize your default values here (if not done with  POGO).
	//------------------------------------------------------------------

	//	Read device properties from database.(Automatic code generation)
	//------------------------------------------------------------------
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("DeviceTaskPeriod"));
	dev_prop.push_back(Tango::DbDatum("NbImgToAlign"));
	dev_prop.push_back(Tango::DbDatum("XTolerance"));
	dev_prop.push_back(Tango::DbDatum("YTolerance"));
	dev_prop.push_back(Tango::DbDatum("SensorPluginType"));
	dev_prop.push_back(Tango::DbDatum("ActuatorSystemDeviceAdress"));
	dev_prop.push_back(Tango::DbDatum("PluginPath"));
	dev_prop.push_back(Tango::DbDatum("CalibrationStepNbXAxis"));
	dev_prop.push_back(Tango::DbDatum("CalibrationStepNbYAxis"));
	dev_prop.push_back(Tango::DbDatum("XPIDDefinition"));
	dev_prop.push_back(Tango::DbDatum("YPIDDefinition"));
	dev_prop.push_back(Tango::DbDatum("DeviceMode"));

	//	Call database and extract values
	//--------------------------------------------
	if (Tango::Util::instance()->_UseDb==true)
		get_db_device()->get_property(dev_prop);
	Tango::DbDatum	def_prop, cl_prop;
	BeamPositionTrackingClass	*ds_class =
		(static_cast<BeamPositionTrackingClass *>(get_device_class()));
	int	i = -1;

	//	Try to initialize DeviceTaskPeriod from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  deviceTaskPeriod;
	else {
		//	Try to initialize DeviceTaskPeriod from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  deviceTaskPeriod;
	}
	//	And try to extract DeviceTaskPeriod value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  deviceTaskPeriod;

	//	Try to initialize NbImgToAlign from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  nbImgToAlign;
	else {
		//	Try to initialize NbImgToAlign from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  nbImgToAlign;
	}
	//	And try to extract NbImgToAlign value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  nbImgToAlign;

	//	Try to initialize XTolerance from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  xTolerance;
	else {
		//	Try to initialize XTolerance from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  xTolerance;
	}
	//	And try to extract XTolerance value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  xTolerance;

	//	Try to initialize YTolerance from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  yTolerance;
	else {
		//	Try to initialize YTolerance from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  yTolerance;
	}
	//	And try to extract YTolerance value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  yTolerance;

	//	Try to initialize SensorPluginType from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  sensorPluginType;
	else {
		//	Try to initialize SensorPluginType from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  sensorPluginType;
	}
	//	And try to extract SensorPluginType value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  sensorPluginType;

	//	Try to initialize ActuatorSystemDeviceAdress from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  actuatorSystemDeviceAdress;
	else {
		//	Try to initialize ActuatorSystemDeviceAdress from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  actuatorSystemDeviceAdress;
	}
	//	And try to extract ActuatorSystemDeviceAdress value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  actuatorSystemDeviceAdress;

	//	Try to initialize PluginPath from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  pluginPath;
	else {
		//	Try to initialize PluginPath from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  pluginPath;
	}
	//	And try to extract PluginPath value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pluginPath;

	//	Try to initialize CalibrationStepNbXAxis from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  calibrationStepNbXAxis;
	else {
		//	Try to initialize CalibrationStepNbXAxis from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  calibrationStepNbXAxis;
	}
	//	And try to extract CalibrationStepNbXAxis value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  calibrationStepNbXAxis;

	//	Try to initialize CalibrationStepNbYAxis from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  calibrationStepNbYAxis;
	else {
		//	Try to initialize CalibrationStepNbYAxis from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  calibrationStepNbYAxis;
	}
	//	And try to extract CalibrationStepNbYAxis value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  calibrationStepNbYAxis;

	//	Try to initialize XPIDDefinition from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  xPIDDefinition;
	else {
		//	Try to initialize XPIDDefinition from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  xPIDDefinition;
	}
	//	And try to extract XPIDDefinition value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  xPIDDefinition;

	//	Try to initialize YPIDDefinition from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  yPIDDefinition;
	else {
		//	Try to initialize YPIDDefinition from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  yPIDDefinition;
	}
	//	And try to extract YPIDDefinition value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  yPIDDefinition;

	//	Try to initialize DeviceMode from class property
	cl_prop = ds_class->get_class_property(dev_prop[++i].name);
	if (cl_prop.is_empty()==false)	cl_prop  >>  deviceMode;
	else {
		//	Try to initialize DeviceMode from default device value
		def_prop = ds_class->get_default_device_property(dev_prop[i].name);
		if (def_prop.is_empty()==false)	def_prop  >>  deviceMode;
	}
	//	And try to extract DeviceMode value from database
	if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  deviceMode;



	//	End of Automatic code generation
	//------------------------------------------------------------------
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "1000", "DeviceTaskPeriod");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "10", "NbImgToAlign");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "pluginType", "SensorPluginType");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "actuator/syst/adrr", "ActuatorSystemDeviceAdress");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "plugin/path", "PluginPath");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "10", "CalibrationStepNbXAxis");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "10", "CalibrationStepNbYAxis");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "false::1::2::3", "XPIDDefinition");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "false::1::2::3", "YPIDDefinition");
	yat4tango::PropertyHelper::create_property_if_empty(this, dev_prop, "SIMULATED", "DeviceMode");


}
//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::always_executed_hook()
// 
// description : 	method always executed before any command is executed
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::always_executed_hook()
{
	if(m_initDone){
		if (m_taskManager){
			// Get task State and Status
			BPTTaskManager::StateStatus stateAndStatus = m_taskManager->i_getStateStatus();
			// Get task beam data 
			BPTTaskManager::ManagerDataPacket managerDataPacket = m_taskManager->i_getManagerDataPacket();
			// Update attributs values 
			m_xBeamPositionInPixels = (short)managerDataPacket.beamDiagnostic.xBeamPostionPixels;
			m_yBeamPositionInPixels = (short)managerDataPacket.beamDiagnostic.yBeamPostionPixels;
			m_computedTime = managerDataPacket.computedTime;

			m_imageHigh = managerDataPacket.beamDiagnostic.imgHigh;
			m_imageWidth = managerDataPacket.beamDiagnostic.imgWidth;
			m_thresholdedImage.clear();
			m_thresholdedImage = managerDataPacket.beamDiagnostic.tresholdedImg;

			set_state(stateAndStatus.state);
			set_status(stateAndStatus.status);
		}
	}	
}
//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_attr_hardware
// 
// description : 	Hardware acquisition for attributes.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_attr_hardware(vector<long> &attr_list)
{
	DEBUG_STREAM << "BeamPositionTracking::read_attr_hardware(vector<long> &attr_list) entering... "<< endl;
		
}
//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_thresholdedImage
// 
// description : 	Extract real attribute values for thresholdedImage acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_thresholdedImage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_thresholdedImage(Tango::Attribute &attr) entering... "<< endl;
	Tango::DevUChar* bufferAttr;

	bufferAttr = &m_thresholdedImage[0];
	attr.set_value(bufferAttr, m_imageHigh, m_imageWidth);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::readm_computedTime
// 
// description : 	Extract real attribute values for computedTime acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_computedTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::readm_computedTime(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_computedTime);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_xAxisTarget
// 
// description : 	Extract real attribute values for xAxisTarget acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_xAxisTarget(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_xAxisTarget(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_target.xTargetPoint);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::write_xAxisTarget
// 
// description : 	Write xAxisTarget attribute values to hardware.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::write_xAxisTarget(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::write_xAxisTarget(Tango::WAttribute &attr) entering... "<< endl;

	Tango::DevShort xTarget;
  	attr.get_write_value(xTarget);

  	m_target.xTargetPoint = (short) xTarget;

  	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_setTrackingTarget(m_target);
		}
	}
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_yAxisTarget
// 
// description : 	Extract real attribute values for yAxisTarget acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_yAxisTarget(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_yAxisTarget(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_target.yTargetPoint);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::write_yAxisTarget
// 
// description : 	Write yAxisTarget attribute values to hardware.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::write_yAxisTarget(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::write_yAxisTarget(Tango::WAttribute &attr) entering... "<< endl;

	Tango::DevShort yTarget;
  	attr.get_write_value(yTarget);

  	m_target.yTargetPoint = (short) yTarget;

  	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_setTrackingTarget(m_target);
		}
	}

}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_xAxisCurrentBeamPosition
// 
// description : 	Extract real attribute values for xAxisCurrentBeamPosition acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_xAxisCurrentBeamPosition(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_xAxisCurrentBeamPosition(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_xBeamPositionInPixels);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_yAxisCurrentBeamPosition
// 
// description : 	Extract real attribute values for yAxisCurrentBeamPosition acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_yAxisCurrentBeamPosition(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_yAxisCurrentBeamPosition(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_yBeamPositionInPixels);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_warningZoneXCenter
// 
// description : 	Extract real attribute values for warningZoneXCenter acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_warningZoneXCenter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_warningZoneXCenter(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_warningZone.xCenter);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::write_warningZoneXCenter
// 
// description : 	Write warningZoneXCenter attribute values to hardware.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::write_warningZoneXCenter(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::write_warningZoneXCenter(Tango::WAttribute &attr) entering... "<< endl;
	Tango::DevDouble xWarningZone;
  	attr.get_write_value(xWarningZone);
	m_warningZone.xCenter = (double) xWarningZone;

	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_setWarningZone(m_warningZone);
		}
	}
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_warningZoneYCenter
// 
// description : 	Extract real attribute values for warningZoneYCenter acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_warningZoneYCenter(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_warningZoneYCenter(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_warningZone.yCenter);

}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::write_warningZoneYCenter
// 
// description : 	Write warningZoneYCenter attribute values to hardware.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::write_warningZoneYCenter(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::write_warningZoneYCenter(Tango::WAttribute &attr) entering... "<< endl;
	Tango::DevDouble yWarningZone;
  	attr.get_write_value(yWarningZone);
	m_warningZone.yCenter = (double) yWarningZone;

	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_setWarningZone(m_warningZone);
		}
	}
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::read_warningZoneRadius
// 
// description : 	Extract real attribute values for warningZoneRadius acquisition result.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::read_warningZoneRadius(Tango::Attribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::read_warningZoneRadius(Tango::Attribute &attr) entering... "<< endl;
	attr.set_value(&m_warningZone.radius);
}

//+----------------------------------------------------------------------------
//
// method : 		BeamPositionTracking::write_warningZoneRadius
// 
// description : 	Write warningZoneRadius attribute values to hardware.
//
//-----------------------------------------------------------------------------
void BeamPositionTracking::write_warningZoneRadius(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "BeamPositionTracking::write_warningZoneRadius(Tango::WAttribute &attr) entering... "<< endl;
	Tango::DevDouble radius;
  	attr.get_write_value(radius);
	m_warningZone.radius = (double) radius;

	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_setWarningZone(m_warningZone);
		}
	}
}

//+------------------------------------------------------------------
/**
 *	method:	BeamPositionTracking::actuator_system_calibration
 *
 *	description:	method to execute "ActuatorSystemCalibration"
 *	Will estimate new ratio on X and Y translation
 *
 *
 */
//+------------------------------------------------------------------
void BeamPositionTracking::actuator_system_calibration()
{
	DEBUG_STREAM << "BeamPositionTracking::actuator_system_calibration(): entering... !" << endl;
	try{
		if(m_initDone){
			if (m_taskManager){
				m_taskManager->i_runSystemCalibration();
			}
		}
	}catch(Tango::DevFailed &df){
		 RETHROW_DEVFAILED(df, "", "", "");
	}
}

//+------------------------------------------------------------------
/**
 *	method:	BeamPositionTracking::start_beam_tracking
 *
 *	description:	method to execute "StartBeamTracking"
 *
 *
 */
//+------------------------------------------------------------------
void BeamPositionTracking::start_beam_tracking()
{
	DEBUG_STREAM << "BeamPositionTracking::start_beam_tracking(): entering... !" << endl;
	try{
		if(m_initDone){
			if (m_taskManager){
				m_taskManager->i_turnTrackingModeOn(m_target);
			}
		}
	}catch(Tango::DevFailed &df){
		 RETHROW_DEVFAILED(df, "", "", "");
	}

}

//+------------------------------------------------------------------
/**
 *	method:	BeamPositionTracking::stop_beam_tracking
 *
 *	description:	method to execute "StopBeamTracking"
 *
 *
 */
//+------------------------------------------------------------------
void BeamPositionTracking::stop_beam_tracking()
{
	DEBUG_STREAM << "BeamPositionTracking::stop_beam_tracking(): entering... !" << endl;
	if(m_initDone){
		if (m_taskManager){
			m_taskManager->i_turnTrackingModeOff();
		}
	}
}
//+------------------------------------------------------------------
/**
 *	method:	BeamPositionTracking::extractPIDCoeffients
 *
 *	description:	method to extract PIDs coefficent values on each axis
 *
 *
 */
//+------------------------------------------------------------------
BPTTaskManager::PIDCoefficient BeamPositionTracking::extractPIDCoeffients(std::string property) throw (std::invalid_argument){

    yat::StringTokenizer st(property, kTOKEN_SEPARATOR);
    string pidOnXInUse = st.next_token();
	BPTTaskManager::PIDCoefficient PIDToReturn;
	if(pidOnXInUse == "true"){
		PIDToReturn.isPIDEnabled = true;

	    PIDToReturn.P = std::stod(st.next_token(),0);
	    PIDToReturn.I = std::stod(st.next_token(),0);
		PIDToReturn.D = std::stod(st.next_token(),0);
	}else{
		PIDToReturn.isPIDEnabled = false;
		PIDToReturn.P =  0;
	    PIDToReturn.I =  0;
		PIDToReturn.D =  0;
	}
	return PIDToReturn;
}


//+------------------------------------------------------------------
/**
 *	method:	BeamPositionTracking::acknowlege_step
 *
 *	description:	method to execute "AcknowlegeStep"
 *	Use this command in simulated mode
 *
 *
 */
//+------------------------------------------------------------------
void BeamPositionTracking::acknowlege_step()
{
	DEBUG_STREAM << "BeamPositionTracking::acknowlege_step(): entering... !" << endl;
	try{
		if(m_initDone){
			if (m_taskManager){
				m_taskManager->i_acknowlegeStep();
			}
		}
	}catch(...){
	}
}




}	//	namespace
